### ISSUE TITLE
Npm install failed - Postinstall huskey

### ISSUE THREAD

**Issue by RobertArissen** [bitmovin/bitmovin-player-react-native#17]
Hello! 👋

While installing the package I get an error related to postinstall huskey. If I remove the postinstall it works fine.
It has to do with the fact that huskey shouldn't be in the release version I expect?

`npm ERR! path /Users/robertarissen/Dev/****/***/node_modules/bitmovin-player-react-native
npm ERR! command failed
npm ERR! command sh -c husky install
npm ERR! husky - .git can't be found (see https://typicode.github.io/husky/#/?id=custom-directory)
`

**Comment by pogist** [comment]
Hello there! 👋

Yes, you're absolutely right. Husky is a development dependency and shouldn't be installed alongside the release package so just keep the `postinstall` hook removed for now. Sorry for the inconvenience 😅.

The problem is that `postinstall` gets executed after every install, even when done from npm.

The right way would be to setup husky at a `prepare` hook, which is executed only locally and therefore is more suitable for development. I'll open a PR for it.

I don't know when the fix will reach npm exactly, so I suggest you to keep track of this change on your project's side using something like [`patch-package`](https://github.com/ds300/patch-package) for now.

Again, sorry for the inconvenience and thanks for pointing this issue out 😁.

**Comment by pogist** [comment]
Hi @RobertArissen 👋

Version [`v0.2.1`](https://www.npmjs.com/package/bitmovin-player-react-native/v/0.2.1) has just been released to npm fixing this installation issue. Please, try it out and let me know if you have any further problems. Thank you.
