### ISSUE TITLE
[Questioin]Can we hide closed caption from settings in Default UI?

### ISSUE THREAD

**Issue by bll-prataps** [bitmovin/bitmovin-player-react-native#82]
is there a way to hide closed caption / subtitle from setting in default UI so it does not show up in UI? Is it in development ?

**Comment by dweinber** [comment]
Hi @bll-prataps,
I'd like to understand the use case a bit better - if the stream has subtitles / closed captions, why would you hide it?

It's currently not supported in the default UI, but you can create a custom UI built using https://github.com/bitmovin/bitmovin-player-ui and remove the subtitle selection completely if you never want to show them.

**Comment by bll-prataps** [comment]
Hi @dweinber ,
Our videos does not have closed captions and in iOS, UI is showing option of closed captions in settings but in android UI does not show any options for closed captions. So thats why i wanted to hide it.
Thank you for the reply.

**Comment by dweinber** [comment]
Thanks for the feedback @bll-prataps. The actual solution for the problem is to add the `CLOSED-CAPTION=NONE` attribute to the `#EXT-X-STREAM-INF` tags in your HLS multivariant playlist. You can find the details around this here: https://bitmovin.com/docs/player/faqs/why-do-i-see-an-additional-cc1-entry-in-the-subtitle-menu-in-safari-ios

However, if you still want to hide the subtitle selection from the UI regardless, what I mention in https://github.com/bitmovin/bitmovin-player-react-native/issues/82#issuecomment-1432789961 will still work.
